name: tests
on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        variant:
          - {os: windows-latest, generator: msvc, arch: x64, config: Release} 

    runs-on: ${{ matrix.variant.os }}
    name: ${{ matrix.variant.os }} / ${{ matrix.variant.generator }} / ${{ matrix.variant.arch }} / ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: A 
        if: matrix.variant.os == 'windows-latest'
        run: |
          .\build.bat
          ls -Recurse
