name: tests
on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        variant:
          - {os: windows-latest, generator: msvc, arch: x64, config: Release} 

    runs-on: ${{ matrix.variant.os }}
    name: ${{ matrix.variant.os }} / ${{ matrix.variant.generator }} / ${{ matrix.variant.arch }} / ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: A 
        if: matrix.variant.os == 'windows-latest'
        run: |
          .\build.bat
      - name: B
        run: |
          ls -Recurse
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: bochscpu_${{ matrix.variant.generator }}_${{ matrix.variant.arch }}_${{ github.sha }}
          path: |
            bxbuild-win/bochscpu-ffi/bochscpu.h*
            bxbuild-win/bochscpu-ffi/target/release
